I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1308, in script
    OW """“您一定要相信我们那，警察兄弟，L是个向来就非常胆小的人，他怎么可能会干的出来那种事呢？”"""
Exception: Sayer 'OW' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1308, in script
    OW """“您一定要相信我们那，警察兄弟，L是个向来就非常胆小的人，他怎么可能会干的出来那种事呢？”"""
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "F:\WorkSpace\Game\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'OW' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
Gm 1.0
Sat Aug 10 17:11:29 2024
